apiVersion: v1
kind: Service
metadata:
  name: {{ include "tideway.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "tideway.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  type: {{ .Values.gateway.service.type }}
  selector:
    app.kubernetes.io/name: {{ include "tideway.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: http
      port: {{ .Values.gateway.service.port }}
      targetPort: {{ .Values.gateway.service.port }}
