apiVersion: v1
kind: Service
metadata:
  name: {{ include "tideway.fullname" . }}
  labels:
    {{- include "tideway.labels" . | nindent 4 }}
spec:
  type: {{ .Values.gateway.service.type }}
  selector:
    {{- include "tideway.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.gateway.service.port }}
      targetPort: http
